---
title: Placeholder^[We thank Richard for providing us with this neat template.]
author:
  - Richard Winter^[University of Mannheim, r.winter@uni-mannheim.de]
date: "`r Sys.Date()`"
abstract: "Abstract goes here."
output:
  bookdown::pdf_document2:
    extra_dependencies: ["amssymb",	"amsmath", "amsfonts", "afterpage", "array", "booktabs", "eurosym", "geometry", "float", "graphicx", "hyperref", "longtable", "caption", "color", "setspace", "comment", "footmisc", "caption", "pdflscape", "subfig", "siunitx", "subfiles"]
    keep_tex: true
    toc: false
bibliography: "bibliography.bib"
biblio-style: "apalike"
link-citations: true
fontsize: 12pt
linkcolor: blue
header-includes:
  - |
    ```{=latex}
    \newtheorem{theorem}{Theorem}
    \newtheorem{corollary}[theorem]{Corollary}
    \newtheorem{proposition}{Proposition}
    \newenvironment{proof}[1][Proof]{\noindent\textbf{#1.} }{\ \rule{0.5em}{0.5em}}
    \newtheorem{hyp}{Hypothesis}
    \newtheorem{subhyp}{Hypothesis}[hyp]
    \renewcommand{\thesubhyp}{\thehyp\alph{subhyp}}
    \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{A\arabic{table}}     \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}
    ```
---

\newpage

<!-- Regarding the YAML Header (Stuff enclosed in '---' above)

^This is how you comment in Rmarkdown btw. Use Ctrl + Shift + C on a selection to comment out.

There are more fields you can use to adjust certain aspects of the paper. For me, the ones specified sufficed.

Note that YAML is quite sensitive to indentations. Don't start a new line for no reason and make sure that nested key:value pairs are correctly aligned.

For a paper I use the bookdown package and the pdf_document2 document format, as it allows me to cross-reference figures and tables, which is not a feature of default rmarkdown.

For knitting, I also use the tinytex package, which worked better for me than the default LaTeX distribution. Might not be the same experience for you, but I read somewhere that it is highly recommended (couldn't be bothered to look for the source).

Bibliography file should be a bib file like you would use with biber LaTeX. Some bibliography software, e.g., Zotero, allows for direct link between R-Project and Zotero library, however, in order to accommodate different software, I implemented citations like this.

extra_dependencies: List type value where you just give the names of the additional LaTeX packages you would like to use. I haven't checked which ones pandoc or whoever runs this in the background includes some of them already by default, some might be reduntant, some you may not need. Adjust at your own discretion.

header-includes allows you to add additional LaTeX code to the preamble. I remember there was something problematic here if you intend to produce multiple output formats, maybe I should check that again. There is also the includes: in-header/in_header variant. One of them only works for pdf document, the other is included in every output format.

-->

<!-- First Time

First knit attempt might take a while, because tinytex needs to install the packages first.

-->

<!-- Set Paths and Globals 

I recommend setting the code-chunk default directory to your Project directory

Go to Tools > Global Options > Rmarkdown and change Evaluate chunks in directory: Project

-->

```{r, include=F}
root <- "../"
# Code chunk option include=F means that the code will not be included in the document and only the side effects will remain

# Some code chunk options you may want to adjust
knitr::opts_chunk$set(
  echo=F, # Print code in your document
  message = F, # If functions throw a message like "successfully loaded" or something
  warning = F, # For stuff like NAs introduced by coercion
  fig.pos = "H", # Here you can set LaTex float specifiers
  fig.align='center') # Figure alignment --> I don't really get how this works for LaTeX documents. Sometimes it works, sometimes not so much

# Some knitting options you may want to adjust
knitr::opts_knit$set(
  root.dir= root # normally, the root directory of a markdown document is the directory where the markdown file is located
                   # If you want to work with relative paths and not get confused by anything, you might want to set this to your project directory every time
  )
```

<!-- Conditional Code Execution 

Some Code might take significant time to run through. I'd recommend putting this in an auxiliary script and only executing it if necessary.

One approach to this end is to add additional booleans for conditional code execution.

-->

```{r bools}
analysis <- T
```

<!-- "Globals" 

You might want to write external scripts or packages for common functions you define for several parts of your paper.

If you want to knit subparts of your paper, you generally might not want to run the main file but only the child rmd on it's own.

-->

<!-- Load Libraries -->

```{r load-libraries}
source("./Scripts/libraries.R")
```

<!-- Define Functions -->

```{r load-functions}
source("./Scripts/functions.R")
```


<!-- Headers 

Headers are defined as # <HEADER>6{#<LABEL>}

The given label can then be referenced within your document using \@ref(label)

-->
# Introduction{#intro}

```{r knit-intro, child = './Markdown/02_Introduction.Rmd'}

```

# Instituional Background{#inst}

```{r knit-inst, child = './Markdown/03_InstitutionalBackground.Rmd'}

```

# Data{#data}

```{r knit-data, child = './Markdown/04_Data.Rmd'}

```

# Empirical Strategy{#strat}

```{r knit-strat, child = './Markdown/05_EmpiricalStrategy.Rmd'}

```

# Results{#res}

<!-- Run lengthy analysis -->

```{r run-analysis, eval = analysis}
source("./Scripts/analysis.R")
```


<!-- If analysis was already performed, as indicated by the analysis variable set above, just load the results -->

```{r load-analysis}
if(!analysis){
  load("./Data/analysis.Rdata")
}
```


```{r knit-results, child = './Markdown/06_Results.Rmd'}

```

# Discussion{#discussion}

```{r knit-discussion, child = './Markdown/07_Discussion.Rmd'}

```

# Conclusion{#conclusion}

```{r knit-conclusion, child = './Markdown/08_Conclusion.Rmd'}

```

# References{-}

<!-- References

Specifying the label as '-' for a section turns off the enumeration, which is especially helpful for references.

By default, Rmarkdown/pandoc/whoever will add the list of references as the last part of the paper. If the references are to be followed by an appendix, Rmarkdown needs to be told to add the references before that. There are probably several ways of doing that, one would be to use HTML tags (works irrespective of the chosen output format).

-->

<div id="refs"></div>

\clearpage

<!-- Appendices 

Bookdown has an extension that allows you to easily add appendices to your paper. You just need to include the line # (APPENDIX) Appendix {-} which indicates that all sections following will be appendix sections.

The numbering style will automatically be changed to A, A.1, B, B.1, etc., however, the numbering of tables and figures will remain unchanged, which might be an undesired feature. Hence, I added the following code I found to the YAML header:

\newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{A\arabic{table}}     \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}

This restarts the counters on figures and tables and adds the letter A for appendix. If you have several appendices, you might want to figure out a different approach that automatically detects the letter of the appendix section.

-->

# (APPENDIX) Appendix {-}

\beginsupplement

# Additional Tables and Figures

```{r, child="./Markdown/Appendix.Rmd"}

```


