---
title: "Results"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    extra_dependencies: ["amssymb",	"amsmath", "amsfonts", "afterpage", "array", "booktabs", "eurosym", "geometry", "float", "graphicx", "hyperref", "longtable", "caption", "color", "setspace", "comment", "footmisc", "caption", "pdflscape", "subfig", "siunitx", "subfiles"]
    keep_tex: true
    toc: false
bibliography: "bibliography.bib"
biblio-style: "apalike"
link-citations: true
fontsize: 12pt
linkcolor: blue
header-includes:
  - |
    ```{=latex}
    \newtheorem{theorem}{Theorem}
    \newtheorem{corollary}[theorem]{Corollary}
    \newtheorem{proposition}{Proposition}
    \newenvironment{proof}[1][Proof]{\noindent\textbf{#1.} }{\ \rule{0.5em}{0.5em}}
    \newtheorem{hyp}{Hypothesis}
    \newtheorem{subhyp}{Hypothesis}[hyp]
    \renewcommand{\thesubhyp}{\thehyp\alph{subhyp}}
    \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{A\arabic{table}}     \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}
    ```
---

```{r, include=F, eval=F}
root <- "../"
# Code chunk option include=F means that the code will not be included in the document and only the side effects will remain

# Some code chunk options you may want to adjust
knitr::opts_chunk$set(
  echo=F, # Print code in your document
  message = F, # If functions throw a message like "successfully loaded" or something
  warning = F, # For stuff like NAs introduced by coercion
  fig.pos = "H", # Here you can set LaTex float specifiers
  fig.align='center') # Figure alignment --> I don't really get how this works for LaTeX documents. Sometimes it works, sometimes not so much

# Some knitting options you may want to adjust
knitr::opts_knit$set(
  root.dir= root # normally, the root directory of a markdown document is the directory where the markdown file is located
                   # If you want to work with relative paths and not get confused by anything, you might want to set this to your project directory every time
  )
```

```{r, results='asis'}
stringi::stri_rand_lipsum(5) %>% paste(collapse = " ") %>% cat()
```

Example for a graph with subplots.

```{r example-plot, fig.cap = "Example Graph with subplots", fig.subcap=c("First Graph","Second Graph"), fig.ncol=2, out.width="50%"}
ggplot(mtcars, aes(mpg,disp,color=factor(cyl))) +
  geom_point() + 
  labs(x="Miles per Gallon",
       y="Engine Displacement",
       color="Cylinders") +
  theme_bw()

ggplot(mtcars, aes(factor(gear))) +
  geom_bar(color="darkblue") + 
  labs(x="Gears",
       y="Count") +
  theme_bw()
```

Example for a regression table

```{r example-table}
msummary(ols_reg)
```

